from setuptools import setup

setup(name='moztrap_connect',
      version='0.1',
      description='MozTrap API Library.',
      author='C. Dawson',
      author_email='cdawson@mozilla.com',
      url='https://github.com/camd/moztrap-connect',
      py_modules=['mtconnect.connect'],
      install_requires=['pytest>=2.2.3', 'requests>=0.11.2'],
      license='Mozilla Public License 2.0 (MPL 2.0)',
      keywords='moztrap test management mozilla',
      classifiers=['Development Status :: 3 - Alpha',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)',
                   'Operating System :: POSIX',
                   'Operating System :: Microsoft :: Windows',
                   'Operating System :: MacOS :: MacOS X',
                   'Topic :: Software Development :: Quality Assurance',
                   'Topic :: Software Development :: Testing',
                   'Topic :: Utilities',
                   'Programming Language :: Python',
                   'Programming Language :: Python :: 2.6',
                   'Programming Language :: Python :: 2.7'])
